/* FILE NAME: BRYPROTO.C version 1.0 */
/* Copyright 1992, Donald Bryson, 3421 Elder Mountain Rd., Chattanooga, TN 37419
Phone: (615) 821-5757, E-Mail dbryson@tclock.com */

/* Accepts name of directory and generates a file named FUNCTION.H that
contains function prototypes for all functions that are typed with the
following format
returntype FunctionName(type name1, type nam2)
{
	functionbody;
	;
	;

}
from each file containing a *.C extension. */

#include <stdio.h>
#include <time.h>
#include <dir.h>
#include <string.h>

#define MAXFILES 128			/* Maximum number of source files */
#define MPATH 128				/* Maximum full path */
#define MAXLINE 256				/* You should never have a maximum line greater than this */

unsigned int BraceCount;		/* Used to determine if inside or outside function */
unsigned int ParenCount;		/* Used to determine end of function parameters */
char Comment;

FILE *outfile;

char FileName[MAXFILES][MPATH];

void CheckFile(char *fn);
void CheckLine(char *String);


void main(int argc, char *argv[]) {
	int done, numfiles, counter;
	time_t t;
	struct ffblk ffblk;

	char StartDir[MPATH];
	char WorkDir[MPATH];

	getcwd(StartDir, MPATH);
	if ( argc == 2 ) {
		strcpy(WorkDir, argv[1]);
		if ( (chdir(WorkDir)) == -1) {
			fprintf(stderr, "Unable to check directory %s\n", WorkDir);
			return;
		}
	} else {
		strcpy(WorkDir, StartDir);
	}

	time(&t);

	fprintf(stdout, "BryProto -- Copyright 1992 Bryson Research and Development\n");
	fprintf(stdout, "3421 Elder Mtn. Rd., Chattanooga TN  37419, (615) 821-5757\n");


	if ( NULL == (outfile=fopen("FUNCTION.H", "w") ) ) {
		return;
	} else {
		fprintf(outfile, "/* Header file generated by BryProto on ");
		fprintf(outfile, "%s", ctime(&t));
	}

	fprintf(outfile, "The following files were checked from the %s directory:\n", WorkDir);

	/* Load up the file names and paths */
	done = findfirst("*.C",&ffblk,0);
	numfiles = 0;
	while (!done) {
		sprintf(FileName[numfiles], "%s", ffblk.ff_name);
		fprintf(outfile, "\t%s\n", ffblk.ff_name);
		done = findnext(&ffblk);
		++numfiles;
	}
	fprintf(outfile, "*/\n\n");

	counter = 0;

	while ( counter < numfiles ) {
		printf("Checking: %s\n", FileName[counter]);
		CheckFile(FileName[counter]);
		++counter;
	}

	chdir(StartDir);
}

void CheckFile(char *fn)
{
	FILE *infile;
	char String[MAXLINE];

	if ( (infile=fopen(fn, "rt")) == NULL) {
		fprintf(stderr, "Unable to open %s\n", fn);
		return;
	}

	fprintf(outfile, "/* Functions from %s */\n", fn);

	while ( fgets(String, MAXLINE, infile) ) {
		CheckLine(String);
	}
	fclose(infile);
	ParenCount = 0;
	BraceCount = 0;
	Comment = 0;
}

void CheckLine(char *String)
{
	char *Ptr;
	int WasComm = 0;
	Ptr = String;

	while ( *Ptr ) {

		switch(*Ptr) {
			case '{':
				++BraceCount;
				break;
			case '}':
				--BraceCount;
				break;
			case '(':
				++ParenCount;
				break;
			case ')':
				--ParenCount;
				break;
			case '*':
				if ( *(Ptr+1) == '/' ) {
					--Comment;
					WasComm = 1;
				}
				break;
			case '/':
				if ( *(Ptr+1) == '*' )
					++Comment;
				break;
		}

		++Ptr;

	}


	if ( Comment || WasComm ) {
		return;
	} else if ( !BraceCount && !ParenCount && strstr(String,"(") && strstr(String,")") ) {
		if ( !(strstr(String, ";")) ) {
			Ptr = String;
			while ( *Ptr != '\n' ) {
				fputc(*Ptr, outfile);
				++Ptr;
			}
			fputs(";\n", outfile);
		}
	} else {
		return;
	}

}
